name: AutoSignIn
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v1
        with: 
            python-version: 3.7
      - name: Install
        run: 
            pip install -r requirements.txt
      - name: Run
        env:
            ACCOUNT: ${{secrets.ACCOUNT}}
        run: |
            sudo cp -p chromedriver /usr/bin/
            chmod -R 777 /usr/bin/chromedriver
            python main.py
